version: "3"

services:
  database:
    build: ./db
    container_name: haskell-data
    ports:
      - "5432:5432"
    env_file:
      - example.env
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
