name: Test CI
on: push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the fucking repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Cache Nix
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build the project
        run:
